[package]
name = "reticula-tdeck"
description = "LILYGO T-Deck (ESP32-S3) board support package for Reticula"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[build-dependencies]
embuild = "0.31"

[dependencies]
reticula-hal = { path = "../reticula-hal" }
embedded-graphics = "0.8"
mipidsi = "0.10"

esp-idf-hal = "0.44"
esp-idf-svc = "0.51"
esp-idf-sys = { version = "0.35", features = ["binstart"] }
esp-idf-sys-macro = "0.3"

log.workspace = true

[lints]
workspace = true